AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'thumbnailr

  '
Globals:
  Function:
    Timeout: 600
Resources:
  QuotaDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: thumbnailr-quota
      AttributeDefinitions:
      - AttributeName: UserID
        AttributeType: S
      KeySchema:
      - AttributeName: UserID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  ThumbnailsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: thumbnailr-thumbnails
      AttributeDefinitions:
      - AttributeName: ID
        AttributeType: S
      KeySchema:
      - AttributeName: ID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  ThumbnailStoreS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: thumbnailr-thumbnailstore-${AWS::AccountId}
  PhotoStoreS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: thumbnailr-photostore-${AWS::AccountId}
  CreationRequestsSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: thumbnailr-creation-requests
  PingFunctionAlb:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-deployment-307390403458/0f7af57ab6bcc06a05600571c6d525b1
      Handler: main
      Runtime: go1.x
  PingFunctionApiGw:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-deployment-307390403458/e6e83904fae7b52f6ae13005de3f20c7
      Handler: main
      Runtime: go1.x
      Events:
        CheckCreationEvent:
          Type: Api
          Properties:
            Path: /ping
            Method: GET
  CheckCreationFunctionAlb:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-deployment-307390403458/9836d760ba6b1a5035a8754267bd484f
      Handler: main
      Runtime: go1.x
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: ThumbnailsDynamoDBTable
  CheckCreationFunctionApiGw:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-deployment-307390403458/1c3ed4af45f6028427aaf3831920a2a4
      Handler: main
      Runtime: go1.x
      Events:
        CheckCreationEvent:
          Type: Api
          Properties:
            Path: /check_creation
            Method: GET
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: ThumbnailsDynamoDBTable
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-deployment-307390403458/1f36dff7a4ec7d0d703bbe1b26a66e2a
      Handler: main
      Runtime: go1.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /get
            Method: GET
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: ThumbnailsDynamoDBTable
      - S3ReadPolicy:
          BucketName:
            Ref: ThumbnailStoreS3Bucket
  RequestCreationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-deployment-307390403458/f655e0f63b1bcdf35862d6325a9319b5
      Handler: main
      Runtime: go1.x
      Events:
        RequestCreationEvent:
          Type: Api
          Properties:
            Path: /request_creation
            Method: POST
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ThumbnailsDynamoDBTable
      - DynamoDBReadPolicy:
          TableName:
            Ref: QuotaDynamoDBTable
      - SNSPublishMessagePolicy:
          TopicName: thumbnailr-creation-requests
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-deployment-307390403458/bd2d8d5ed3037ce41840782bcc204919
      Handler: main
      Runtime: go1.x
      MemorySize: 512
      Timeout: 5
      Events:
        LogEntryEvent:
          Type: SNS
          Properties:
            Topic:
              Ref: CreationRequestsSNSTopic
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ThumbnailsDynamoDBTable
      - DynamoDBCrudPolicy:
          TableName:
            Ref: QuotaDynamoDBTable
      - S3ReadPolicy:
          BucketName:
            Ref: PhotoStoreS3Bucket
      - S3CrudPolicy:
          BucketName:
            Ref: ThumbnailStoreS3Bucket
