AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'thumbnailr

  '
Globals:
  Function:
    Timeout: 600
    MemorySize: 192
Resources:
  QuotaDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: thumbnailr-quota
      AttributeDefinitions:
      - AttributeName: UserID
        AttributeType: S
      KeySchema:
      - AttributeName: UserID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  ThumbnailsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: thumbnailr-thumbnails
      AttributeDefinitions:
      - AttributeName: ID
        AttributeType: S
      KeySchema:
      - AttributeName: ID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  ThumbnailStoreS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: thumbnailr-thumbnailstore-${AWS::AccountId}
  PhotoStoreS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: thumbnailr-photostore-${AWS::AccountId}
  CreationRequestsSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: thumbnailr-creation-requests
  PingFunctionAlb:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-deployment-307390403458/1881198a817af0106bbb8c176193ff9d
      Handler: main
      Runtime: go1.x
  PingFunctionApiGw:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-deployment-307390403458/34e6ea5551ed9d8ce54a26e9c334c6d6
      Handler: main
      Runtime: go1.x
      Events:
        CheckCreationEvent:
          Type: Api
          Properties:
            Path: /ping
            Method: GET
  CheckCreationFunctionAlb:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-deployment-307390403458/38382951fbab4a066cb7b378b6583613
      Handler: main
      Runtime: go1.x
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: ThumbnailsDynamoDBTable
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-deployment-307390403458/831fe99e1323c73be2f20455c77e27a6
      Handler: main
      Runtime: go1.x
      Events:
        AuthEvent:
          Type: Api
          Properties:
            Path: /token
            Method: POST
  CheckCreationFunctionApiGw:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-deployment-307390403458/d92569b964926a788d8848435922bbca
      Handler: main
      Runtime: go1.x
      Events:
        CheckCreationEvent:
          Type: Api
          Properties:
            Path: /check_creation
            Method: GET
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: ThumbnailsDynamoDBTable
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-deployment-307390403458/486c4e371ad9848556e6fe8fffb4fd28
      Handler: main
      Runtime: go1.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /get
            Method: GET
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: ThumbnailsDynamoDBTable
      - S3ReadPolicy:
          BucketName:
            Ref: ThumbnailStoreS3Bucket
  RequestCreationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-deployment-307390403458/c39c1a109399d5dd7c0ed85069bc2e5f
      Handler: main
      Runtime: go1.x
      Events:
        RequestCreationEvent:
          Type: Api
          Properties:
            Path: /request_creation
            Method: POST
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ThumbnailsDynamoDBTable
      - DynamoDBCrudPolicy:
          TableName:
            Ref: QuotaDynamoDBTable
      - SNSCrudPolicy:
          TopicName: thumbnailr-creation-requests
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-deployment-307390403458/7b5a1f4c28612e8c91b4709ced7c0077
      Handler: main
      Runtime: go1.x
      Events:
        LogEntryEvent:
          Type: SNS
          Properties:
            Topic:
              Ref: CreationRequestsSNSTopic
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ThumbnailsDynamoDBTable
      - DynamoDBCrudPolicy:
          TableName:
            Ref: QuotaDynamoDBTable
      - S3ReadPolicy:
          BucketName:
            Ref: PhotoStoreS3Bucket
      - S3CrudPolicy:
          BucketName:
            Ref: ThumbnailStoreS3Bucket
Outputs:
  ApiGatewayURL:
    Description: API Gateway URL for Production Stage
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
