AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  thumbnailr

Resources:

  QuotaDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: thumbnailr-quota
      AttributeDefinitions:
        -
          AttributeName: "UserID"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "UserID"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ThumbnailsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: thumbnailr-thumbnails
      AttributeDefinitions:
        -
          AttributeName: "ID"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "ID"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ThumbnailStoreS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: thumbnailr-thumbnailstore

  PhotoStoreS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: thumbnailr-photostore

  CreationRequestsSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "thumbnailr-creation-requests"

  CheckCreationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/check_creation/main.zip
      Handler: main
      Runtime: go1.x
      Events:
        CheckCreationEvent:
          Type: Api
          Properties:
            Path: /check_creation
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ThumbnailsDynamoDBTable

  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/get/main.zip
      Handler: main
      Runtime: go1.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /get
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ThumbnailsDynamoDBTable
        - S3ReadPolicy:
            BucketName: !Ref ThumbnailStoreS3Bucket

  RequestCreationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/request_creation/main.zip
      Handler: main
      Runtime: go1.x
      Events:
        RequestCreationEvent:
          Type: Api
          Properties:
            Path: /request_creation
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ThumbnailsDynamoDBTable
        - DynamoDBReadPolicy:
            TableName: !Ref QuotaDynamoDBTable
        - SNSPublishMessagePolicy:
            TopicName: "thumbnailr-creation-requests"

  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/create/main.zip
      Handler: main
      Runtime: go1.x
      Events:
        LogEntryEvent:
          Type: SNS
          Properties:
            Topic: !Ref CreationRequestsSNSTopic
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ThumbnailsDynamoDBTable
        - DynamoDBCrudPolicy:
            TableName: !Ref QuotaDynamoDBTable
        - S3ReadPolicy:
            BucketName: !Ref PhotoStoreS3Bucket
        - S3CrudPolicy:
            BucketName: !Ref ThumbnailStoreS3Bucket

